### ISSUE TITLE
试了下好像并没有自动按下

### ISSUE THREAD

**Issue by devnakx** [Alex1911-Jiang/GenshinBalladsOfBreezeAider#1]
跟着食用方法做了几次，都没有成功

**Comment by H-K-Y** [comment]
我试了一下也不行，后来把游戏改成1920*1080，然后用管理员权限启动辅助程序就行了

**Comment by devnakx** [comment]
嗯，管理员启动确实可以了，不过用了下好像困难模式会漏掉两个

**Comment by Alex1911-Jiang** [comment]
原来还对权限有要求吗...一直Debug没有发现, 我先改下运行权限配置, 漏掉的问题我再看看

**Comment by Alex1911-Jiang** [comment]
漏掉的问题, 如果是卡顿导致没按到的话, 建议关掉垂直同步试试

**Comment by devnakx** [comment]
我垂直同步一直都是关着的……我基本所有游戏进游戏第一件事就是关垂直同步

**Comment by devnakx** [comment]
漏掉的主要是两个快速连续的圈

**Comment by Alex1911-Jiang** [comment]
你看一下另一个Issues是不是你的情况...
[https://github.com/Alex1911-Jiang/GenshinBalladsOfBreezeAider/issues/2](url)

**Comment by devnakx** [comment]
对的

**Comment by Alex1911-Jiang** [comment]
拿一下最新版看看解决了没有

**Comment by devnakx** [comment]
晨曦朝露大师难度好像会漏掉一个，但是我后面又试了两次，一个都没漏了，应该没问题了
