### ISSUE TITLE
似乎同一按键连续两次很近就会失败

### ISSUE THREAD

**Issue by 1764421284** [Alex1911-Jiang/GenshinBalladsOfBreezeAider#2]
RT

**Comment by 1764421284** [comment]
另附：似乎30帧时会比60好些

**Comment by Alex1911-Jiang** [comment]
嗯, 我找了差一点的电脑也能试出这个情况, 暂时同一个键先加了50毫秒的冷却, 避免键按下去了屏幕还没刷新又按一次的情况, 但是又偶尔会出现卡顿导致第二下按不到的情况, 似乎关闭垂直同步能有点改善

**Comment by 1764421284** [comment]
> 嗯, 我找了差一点的电脑也能试出这个情况, 暂时同一个键先加了50毫秒的冷却, 避免键按下去了屏幕还没刷新又按一次的情况, 但是又偶尔会出现卡顿导致第二下按不到的情况, 似乎关闭垂直同步能有点改善

试了下确实好多了
但是困难难度底第12个那样的还是失败

**Comment by Alex1911-Jiang** [comment]
嗯, 一直在试大师忽略了困难还有比大师更复杂的情况
这个问题的原因是两个圈太近的时候第二个圈的颜色影响到了第一个圈, 导致第一个圈不是黄色而是偏白的颜色
我把受影响的颜色也加入到判定范围内了, 拿最新版试下吧
