### ISSUE TITLE
能否改为热键启动?

### ISSUE THREAD

**Issue by dfaofeng** [Alex1911-Jiang/GenshinBalladsOfBreezeAider#3]
目前看还好,但是每次要切过来点启动就有点麻烦,还有有时候会突然连续错误3次,不过能拿奖励无所谓了

**Comment by Alex1911-Jiang** [comment]
加了, 拿一下最新的Release吧, 按F10启动
错误3次的是哪首歌? 我查一下

**Comment by dfaofeng** [comment]
> 加了, 拿一下最新的Release吧, 按F10启动 错误3次的是哪首歌? 我查一下

魈的那首,最高难度

**Comment by Alex1911-Jiang** [comment]
> > 加了, 拿一下最新的Release吧, 按F10启动 错误3次的是哪首歌? 我查一下
> 
> 魈的那首,最高难度

改了
